SELECT * FROM [customer_behaviour_analysis].[dbo].[customer]

--Q1 what is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as  Total_revenue
from customer
group by gender

--Q2which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3 which ar ethe top 5 products with the highest average review rating?
--using top 5
select top 5 item_purchased, round(avg(review_rating),2) as avg_review_rating
from customer
group by item_purchased
order by avg(review_rating) desc

--Q4 compare the average purcahse amounts between standard and express shipping.
select shipping_type, round(avg(purchase_amount),2) as Avg_amount_spend
from customer
where shipping_type in ('Standard', 'Express')
group by (shipping_type) 

--Q5 Do subscribed customers spend more ? compare average spend and total revenue between subscribers  and non-subcribers
select subscription_status, 
       count(customer_id) AS total_customers,
	   avg(purchase_amount) as avg_spend, 
	   sum(purchase_amount) as total_revenue
from customer
group by subscription_status
order by avg_spend, total_revenue desc

--Q6 which 5 products  have the highest percentage of purchases with dicounts applied?
select top 5 item_purchased, round(sum(case when discount_applied = 'Yes' then 1 else 0 end) * 100/count(*) ,2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc

--Q7 segment customers into new, Returing, and loyal based on their total number of previous purchases , and show the count of each segments?
--Using CTE's
with Customer_segment as(
select customer_id,
       previous_purchases,
     case when previous_purchases = 1 then 'New' 
          when previous_purchases between 2 and 10 then 'Returing'
          else 'Loyal'
          END as Customer_Loyality
from customer
)

select Customer_loyality, count(*)
from customer_segment
group by Customer_loyality 

--case using directly in group by
select   
     case when previous_purchases = 1 then 'New' 
          when previous_purchases between 2 and 10 then 'Returing'
          else 'Loyal'
          END as Customer_Loyality,
          count(*) as Segment_count
from customer
group by case when previous_purchases = 1 then 'New' 
          when previous_purchases between 2 and 10 then 'Returing'
          else 'Loyal'
          END
order by Segment_count DESC

--Q8 What are the top 3 most purchased products within each category
With item_counts as 
(
select category, item_purchased, count(customer_id) as total_customers,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category, item_purchased
) 

select category, item_purchased, item_rank, total_customers from item_counts 
where item_rank <=3

--Q9 customers who are repeated buyers (more than 5 previous orders) also likely to subscribe ?
select subscription_status,
       count(customer_id) as total_Customers
       from customer
where previous_purchases > 5 
group by subscription_status

--Q10 What is the revenue  contribution of each age group?
select  sum(purchase_amount) as Total_revenue,
         case when age between 18 and 30 then 'Adults' 
            when age between 30 and 50 then 'Middle aged'
            else 'seniors'
            end as  age_segment
  from customer

  group by  case when age between 18 and 30 then 'Adults' 
            when age between 30 and 50 then 'Middle aged'
            else 'seniors'
            end 

select  age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc



